# ruff.toml (standalone config file)

# Global settings
line-length = 100
fix = true  # allow auto-fixes where possible

[lint]
# E = pycodestyle, F = pyflakes, I = isort (import sorting)
select = ["E", "F", "I"]

[lint.isort]
# Treat these as first-party once apps exist
known-first-party = ["core", "users", "config"]
combine-as-imports = true
